# Generated by Django 5.0.2 on 2024-03-19 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_acc', models.CharField(max_length=20, unique=True)),
                ('ad_psw', models.CharField(max_length=20)),
                ('is_super', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('o_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=3)),
                ('paid_time', models.DateTimeField(blank=True, null=True)),
                ('o_time', models.DateTimeField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=20)),
                ('s_acc', models.CharField(max_length=20, unique=True)),
                ('s_psw', models.CharField(max_length=20)),
                ('s_phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'shops',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_acc', models.CharField(max_length=20, unique=True)),
                ('u_name', models.CharField(max_length=20)),
                ('u_psw', models.CharField(max_length=20)),
                ('u_sex', models.CharField(max_length=6)),
                ('u_phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=20)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('p_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.productcategories')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ShopProducts',
            fields=[
                ('shop_product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_desc', models.TextField()),
                ('product_status', models.CharField(max_length=2)),
                ('product_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_quantity', models.IntegerField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.products')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.shops')),
            ],
            options={
                'db_table': 'shop_products',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('current_single_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.shopproducts')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.shops')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
        migrations.CreateModel(
            name='UserAddresses',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.users')),
            ],
            options={
                'db_table': 'user_addresses',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.users'),
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.shops')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.users')),
            ],
            options={
                'db_table': 'followers',
                'unique_together': {('u', 's')},
            },
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.shopproducts')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.shops')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.users')),
            ],
            options={
                'db_table': 'carts',
                'unique_together': {('user', 'product', 'shop')},
            },
        ),
    ]
